<?
$news = array(
	'124' => '/news/90-zamena-sensornih-ekranov-i-korpusa.html',
	'125' => '/news/89-lechenie-sinego-ekrana-ili-blue-screen-of-death.html',
	'122' => '/news/88-apgreyd-kompyutera-ustanovka-novoy-videokarti-i-ssd.html',
	'121' => '/news/87-diagnostika-i-remont-gestkogo-diska.html',
	'120' => '/news/86-chistka-kompyutera-ot-pili.html',
	'119' => '/news/85-remont-noutbuka-posle-razlitiya-gidkosti-na-klaviaturu.html',
	'118' => '/news/84-remont-i-diagnostika-kitayskogo-apple.html',
	'117' => '/news/83-spasenie-monitora.html',
	'114' => '/news/82-noutbuk-hp-pavilion-15e011sr.html',
	'112' => '/news/81-noutbuk-apple-macbook-pro-late-2011.html',
	'111' => '/news/80-noutbuk-dell-pp20l.html',
	'110' => '/news/79-zamena-matritsi-na-noutbuke-samsung-np355.html',
	'109' => '/news/78-srochniy-remont-noutbuka-zamena-matritsi-v-noutbuke-asus-x52n.html',
	'108' => '/news/77-remont-noutbuka-asus-x50vl.html',
	'107' => '/news/76-sensatsiya!-sluchaynost-spasla-noutbuk-toshiba-satellite-a300.html',
	'106' => '/news/75-spasenie-noutbuka-toshiba-satellite-a210-ot-posledstviy-zali.html',
	'105' => '/news/74-remont-noutbuka-hp-pavilion-dv7.html',
	'104' => '/news/73-remont-ibp-mustek-powermust-1000-offline.html',
	'103' => '/news/72-zamena-matritsi-na-noutbuke-hp-g52.html',
	'102' => '/news/71-zamena-sistemi-ohlagdeniya-na-noutbuke-hp-g62b12er.html',
	'101' => '/news/70-zamena-matritsi-v-noutbuke-lenovo-g560-simferopol.html',
	'100' => '/news/69-remont-materinskoy-plati-noutbuka-aspire-6530.html',
	'99' => '/news/68-pereproshivka-biosa-toshiba-satellite-a210.html',
	'98' => '/news/67-remont-noutbuka-acer-aspire-5733-simferopol.html',
	'97' => '/news/66-remont-noutbuka-asus-x54c-simferopol.html',
	'96' => '/news/65-spasenie-noutbuka-hp-4510s-ot-zalitiya.html',
	'94' => '/news/64-remont-planshetnogo-netbuka-asus-eee-t101mt.html',
	'93' => '/news/63-nastroyka-noutbuka-lenovo-b575.html',
	'92' => '/news/62-remont-noutbuka-lenovo-g560.html',
	'91' => '/news/61-nastroyka-noutbuka-asus-x50z.html',
	'90' => '/news/60-remont-videokarti-ati-radeon-2900-gt.html',
	'89' => '/news/59-remont-noutbuka-acer-extensa-5220.html',
	'88' => '/news/58-apgreyd-starogo-kompyutera.html',
	'87' => '/news/57-apgreyd-kompyutera.html',
	'86' => '/news/56-remont-noutbuka-acer-aspire-5735.html',
	'85' => '/news/55-remont-noutbuka-asus-k50in.html',
	'84' => '/news/54-remont-noutbuka-asus-x80l.html',
	'83' => '/news/53-remont-netbuka-acer-aspire-one-pav70.html',
	'82' => '/news/52-remont-noutbuka-dell-m5040.html',
	'81' => '/news/51-remont-noutbuka-acer-aspire-8735g.html',
	'80' => '/news/50-remont-noutbuka-hp-compaq-6720s.html',
	'79' => '/news/49-remont-noutbuka-hp-625.html',
	'78' => '/news/48-apgreyd-starogo-kompyutera.html',
	'77' => '/news/47-remont-noutbuka-samsung-r730.html',
	'76' => '/news/46-remont-noutbuka-samsung-q70.html',
	'75' => '/news/45-nastroyka-i-apgreyd-hp-compaq-nx7300.html',
	'74' => '/news/44-remont-noutbuka-sony-vaio-vpcy2.html',
	'72' => '/news/43-ustranenie-neispravnosti-v-noutbuke-fujitsusiemens-v2010.html',
	'71' => '/news/42-remont-netbuk-acer-aspire-one-ze6.html',
	'70' => '/news/41-remont-noutbuka-dell-d630-zamena-matritsi.html',
	'69' => '/news/40-remont-noutbuka-fujitsu-siemens-v5515.html',
	'68' => '/news/39-nastroyka-noutbuka-hp-pavilion-dv1000.html',
	'67' => '/news/38-remont-noutbuka-asus-k50id.html',
	'66' => '/news/37-remont-noutbuka-asus-k51ac.html',
	'65' => '/news/36-remont-noutbuka-lenovo-g530.html',
	'64' => '/news/35-remont-noutbuka-packard-bell-easynote-lj71.html',
	'73' => '/news/34-remont-noutbuka-hp-pavilion-dv7.html',
	'62' => '/news/33-remont-i-noutbuka-asus-m51t.html',
	'60' => '/news/32-remont-noutbuka-lenovo-g550-zamena-yugnogo-mosta.html',
	'59' => '/news/31-remont-noutbuka-asus-a52j.html',
	'58' => '/news/30-remon-noutbka-asus-k52jk.html',
	'57' => '/news/29-remon-noutbuka-lenovo-g550.html',
	'56' => '/news/28-nastroyka-android-na-telefone-samsung-galaxy-s2.html',
	'55' => '/news/27-remont-noutbuka-hp-pavilion-zd8000-defekti-zvuka.html',
	'54' => '/news/26-remont-noutbuka-asus-k50c-posle-grozi.html',
	'53' => '/news/25-remont-noutbuka-lenovo-3000-g530.html',
	'52' => '/news/24-pervie-shagi-v-netbuke-asus-eee-pc-x101ch.html',
	'51' => '/news/23-remont-ibp-mustek-powermust.html',
	'50' => '/news/22-remont-noutbuka-acer-aspire-5553g-zamena-matritsi.html',
	'48' => '/news/21-zamena-matritsi-netbuka-acer-emashines-25001g16i.html',
	'49' => '/news/20-srochniy-remont-noutbuka-v-simferopole.html',
	'46' => '/news/19-remont-i-apgreyd-noutbuka-toshiba-satellite-a10.html',
	'45' => '/news/18-remont-geskogo-diska-noutbuka-acer-aspire-5100.html',
	'44' => '/news/17-zamena-matritsi-noutbuka-asus-n71v.html',
	'43' => '/news/16-remont-razyoma-pitaniya-noutbuka-asus-f6e.html',
	'42' => '/news/15-remont-noutbuka-samsung-npr522h.html',
	'41' => '/news/14-ustranenie-nepoladok-v-netbuke-acer-aspire-one-gz5.html',
	'40' => '/news/13-uspeshniy-remont-noutbuka-hp-omnibook-xe3.html',
	'39' => '/news/12-apple-macbook-pro-13-remont-noutbuka.html',
	'38' => '/news/11-asus-t57pro--aktivno-i-uspeshno-pochinili-uge-7sht.html',
	'37' => '/news/10-acer-aspire-5105awlmi-otremontirovan-za-30-min.html',
	'36' => '/news/9-noutbuk-samsung-r25-i-sgorevshaya-videokarta.html',
	'35' => '/news/8-remont-noutbuka-lenovo-g550-ne-vklyuchaetsya.html',
	'34' => '/news/7-lenovo-s100-zamena-matritsi-101-led-slim-simferopl.html',
	'33' => '/news/6-remont-ibp-ups-simferopol-ul-severnaya.html',
	'32' => '/news/5-zalitiy-gelem-dlya-dusha-noutbuk-acer-aspire-s3.html',
	'31' => '/news/4-matritsa-pod-zakaz-dlya-noutbuka-sony-vaio-vpcea36fm--w-14.html',
	'30' => '/news/3-remont-kompyutera-na-domu-simferopol-ul-gelyabova.html',
	'29' => '/news/2-zamena-matritsi-v-noutbuke-lenovo-thinkpad-sl410.html',
	'28' => '/news/1-remont-kompyutera-na-domu-simferopol-ul-raketnaya.html',
);

if(isset($_GET['id'])){
	$id = intval($_GET['id']);
	if(array_key_exists($id, $news)){
		header('HTTP/1.1 301 Moved Permanently');
		header ('Location: '.$news[$id]);
	}else{
		header("Location: /404.html");
	}
}else{
	header('HTTP/1.1 301 Moved Permanently');
	header ('Location: /news/');
}
?>